env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - babel
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  react/jsx-uses-vars:
    - error
